---

- add_host:
    name: responder
    ansible_host: "{{ cloud_vpn_responder_public_ip }}"
    ansible_user: "{{ cloud_vpn_responder_user }}"
    ansible_connection: "{{ cloud_vpn_responder_ansible_connection }}"
    ansible_network_os: asa
    ansible_ssh_private_key_file: "{{ cloud_vpn_responder_ssh_private_key_file }}"

- name: Wait for SSH port to be reachable
  wait_for:
    host: "{{ cloud_vpn_responder_public_ip }}"
    port: 22

- name: Pause for SSH daemon to settle and accept connections
  pause:
    seconds: "{{ cloud_vpn_pause_before_config_seconds }}"

